### ISSUE TITLE
Rename advantage

### ISSUE THREAD

**Issue by szepeviktor** [warehouseman/semver_bash#1]
Hello @martinhbramwell 

By moving the repo back here and renaming this one causes GitHub to automatically redirect visitors to the new name which is *not* the case now.

**Comment by szepeviktor** [comment]
BTW semver_shell has no "Issues" enabled.

**Comment by martinhbramwell** [comment]
I have activated the "issues".

I thought I had done the right thing in renaming.  I don't full understand your suggestion, and don't know what to do to reverse what I did and then redo it correctly.

If I get delete of this repo, will we get back the auto-redirect, or will it just make things worse?

**Comment by szepeviktor** [comment]
If you go to https://github.com/warehouseman/semver_bash/settings there is a Rename field.

But wait! It seems you have created an repo named `semver_bash` **after** the rename.
Simply  renaming was enough, GitHub does the rest.

Try deleting this repo and see whether the automatic redirection steps in. If not try to contact GitHub support.

**Comment by szepeviktor** [comment]
All the best to you!
